# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'categories.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ManageCategoriesDialog(object):
    def setupUi(self, ManageCategoriesDialog):
        ManageCategoriesDialog.setObjectName("ManageCategoriesDialog")
        ManageCategoriesDialog.resize(624, 480)
        self.buttonBox = QtWidgets.QDialogButtonBox(ManageCategoriesDialog)
        self.buttonBox.setGeometry(QtCore.QRect(530, 10, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(ManageCategoriesDialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(ManageCategoriesDialog)
        self.widget.setGeometry(QtCore.QRect(10, 40, 511, 361))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.listCategories = QtWidgets.QListWidget(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listCategories.setFont(font)
        self.listCategories.setObjectName("listCategories")
        self.gridLayout.addWidget(self.listCategories, 1, 0, 1, 1)
        self.listTriggers = QtWidgets.QListWidget(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listTriggers.setFont(font)
        self.listTriggers.setObjectName("listTriggers")
        self.gridLayout.addWidget(self.listTriggers, 1, 1, 1, 1)
        self.listOverrides = QtWidgets.QListWidget(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listOverrides.setFont(font)
        self.listOverrides.setObjectName("listOverrides")
        self.gridLayout.addWidget(self.listOverrides, 1, 2, 1, 1)
        self.edtCategory = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edtCategory.setFont(font)
        self.edtCategory.setObjectName("edtCategory")
        self.gridLayout.addWidget(self.edtCategory, 2, 0, 1, 1)
        self.edtTrigger = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edtTrigger.setFont(font)
        self.edtTrigger.setObjectName("edtTrigger")
        self.gridLayout.addWidget(self.edtTrigger, 2, 1, 1, 1)
        self.edtOverride = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edtOverride.setFont(font)
        self.edtOverride.setObjectName("edtOverride")
        self.gridLayout.addWidget(self.edtOverride, 2, 2, 1, 1)
        self.widget1 = QtWidgets.QWidget(ManageCategoriesDialog)
        self.widget1.setGeometry(QtCore.QRect(10, 410, 511, 56))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnNewCategory = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnNewCategory.setFont(font)
        self.btnNewCategory.setObjectName("btnNewCategory")
        self.gridLayout_2.addWidget(self.btnNewCategory, 0, 0, 1, 1)
        self.btnRenameCategory = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRenameCategory.setFont(font)
        self.btnRenameCategory.setObjectName("btnRenameCategory")
        self.gridLayout_2.addWidget(self.btnRenameCategory, 0, 1, 1, 1)
        self.btnNewTrigger = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnNewTrigger.setFont(font)
        self.btnNewTrigger.setObjectName("btnNewTrigger")
        self.gridLayout_2.addWidget(self.btnNewTrigger, 0, 2, 1, 1)
        self.btnRenameTrigger = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRenameTrigger.setFont(font)
        self.btnRenameTrigger.setObjectName("btnRenameTrigger")
        self.gridLayout_2.addWidget(self.btnRenameTrigger, 0, 3, 1, 1)
        self.btnNewOverride = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnNewOverride.setFont(font)
        self.btnNewOverride.setObjectName("btnNewOverride")
        self.gridLayout_2.addWidget(self.btnNewOverride, 0, 4, 1, 1)
        self.btnRenameOverride = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRenameOverride.setFont(font)
        self.btnRenameOverride.setObjectName("btnRenameOverride")
        self.gridLayout_2.addWidget(self.btnRenameOverride, 0, 5, 1, 1)
        self.btnDeleteCategory = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDeleteCategory.setFont(font)
        self.btnDeleteCategory.setObjectName("btnDeleteCategory")
        self.gridLayout_2.addWidget(self.btnDeleteCategory, 1, 0, 1, 1)
        self.btnDeleteTrigger = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDeleteTrigger.setFont(font)
        self.btnDeleteTrigger.setObjectName("btnDeleteTrigger")
        self.gridLayout_2.addWidget(self.btnDeleteTrigger, 1, 2, 1, 1)
        self.btnDeleteOverride = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDeleteOverride.setFont(font)
        self.btnDeleteOverride.setObjectName("btnDeleteOverride")
        self.gridLayout_2.addWidget(self.btnDeleteOverride, 1, 4, 1, 1)

        self.retranslateUi(ManageCategoriesDialog)
        self.buttonBox.accepted.connect(ManageCategoriesDialog.accept)
        self.buttonBox.rejected.connect(ManageCategoriesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ManageCategoriesDialog)

    def retranslateUi(self, ManageCategoriesDialog):
        _translate = QtCore.QCoreApplication.translate
        ManageCategoriesDialog.setWindowTitle(_translate("ManageCategoriesDialog", "Dialog"))
        self.label.setText(_translate("ManageCategoriesDialog", "Manage Categories"))
        self.label_3.setText(_translate("ManageCategoriesDialog", "Categories"))
        self.label_4.setText(_translate("ManageCategoriesDialog", "Triggers"))
        self.label_2.setText(_translate("ManageCategoriesDialog", "Overrides"))
        self.listCategories.setSortingEnabled(True)
        self.listTriggers.setSortingEnabled(True)
        self.listOverrides.setSortingEnabled(True)
        self.btnNewCategory.setText(_translate("ManageCategoriesDialog", "New Cat"))
        self.btnRenameCategory.setText(_translate("ManageCategoriesDialog", "Ren Cat"))
        self.btnNewTrigger.setText(_translate("ManageCategoriesDialog", "New Trigger"))
        self.btnRenameTrigger.setText(_translate("ManageCategoriesDialog", "Ren Trigger"))
        self.btnNewOverride.setText(_translate("ManageCategoriesDialog", "New Over"))
        self.btnRenameOverride.setText(_translate("ManageCategoriesDialog", "Ren Over"))
        self.btnDeleteCategory.setText(_translate("ManageCategoriesDialog", "Del Cat"))
        self.btnDeleteTrigger.setText(_translate("ManageCategoriesDialog", "Del Trigger"))
        self.btnDeleteOverride.setText(_translate("ManageCategoriesDialog", "Del Over"))

