# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'readcheckfile.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReadCheckFileDialog(object):
    def setupUi(self, ReadCheckFileDialog):
        ReadCheckFileDialog.setObjectName("ReadCheckFileDialog")
        ReadCheckFileDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ReadCheckFileDialog.resize(967, 572)
        ReadCheckFileDialog.setMaximumSize(QtCore.QSize(967, 585))
        ReadCheckFileDialog.setModal(True)
        self.label = QtWidgets.QLabel(ReadCheckFileDialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 221, 31))
        self.label.setObjectName("label")
        self.filePathEdit = QtWidgets.QLineEdit(ReadCheckFileDialog)
        self.filePathEdit.setGeometry(QtCore.QRect(240, 10, 611, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filePathEdit.setFont(font)
        self.filePathEdit.setObjectName("filePathEdit")
        self.listCategories = QtWidgets.QListWidget(ReadCheckFileDialog)
        self.listCategories.setGeometry(QtCore.QRect(860, 70, 101, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listCategories.setFont(font)
        self.listCategories.setObjectName("listCategories")
        self.layoutWidget = QtWidgets.QWidget(ReadCheckFileDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 44, 841, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listCategorized = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listCategorized.setFont(font)
        self.listCategorized.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listCategorized.setAutoFillBackground(False)
        self.listCategorized.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.listCategorized.setAlternatingRowColors(True)
        self.listCategorized.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listCategorized.setViewMode(QtWidgets.QListView.ListMode)
        self.listCategorized.setObjectName("listCategorized")
        self.verticalLayout.addWidget(self.listCategorized)
        self.edtSelectTrigger = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.edtSelectTrigger.setFont(font)
        self.edtSelectTrigger.setObjectName("edtSelectTrigger")
        self.verticalLayout.addWidget(self.edtSelectTrigger)
        self.listUnCategorized = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listUnCategorized.setFont(font)
        self.listUnCategorized.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listUnCategorized.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.listUnCategorized.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listUnCategorized.setObjectName("listUnCategorized")
        self.verticalLayout.addWidget(self.listUnCategorized)
        self.layoutWidget1 = QtWidgets.QWidget(ReadCheckFileDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(860, 10, 101, 61))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnReadCheckFile = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnReadCheckFile.setFont(font)
        self.btnReadCheckFile.setObjectName("btnReadCheckFile")
        self.verticalLayout_3.addWidget(self.btnReadCheckFile)
        self.btnUnCat = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnUnCat.setFont(font)
        self.btnUnCat.setObjectName("btnUnCat")
        self.verticalLayout_3.addWidget(self.btnUnCat)
        self.btnAccept = QtWidgets.QPushButton(ReadCheckFileDialog)
        self.btnAccept.setGeometry(QtCore.QRect(755, 546, 101, 23))
        self.btnAccept.setObjectName("btnAccept")
        self.layoutWidget2 = QtWidgets.QWidget(ReadCheckFileDialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(864, 390, 101, 181))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnSetTrigger = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSetTrigger.setFont(font)
        self.btnSetTrigger.setObjectName("btnSetTrigger")
        self.verticalLayout_2.addWidget(self.btnSetTrigger)
        self.btnSetCat = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSetCat.setFont(font)
        self.btnSetCat.setObjectName("btnSetCat")
        self.verticalLayout_2.addWidget(self.btnSetCat)
        self.edtNewCat = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edtNewCat.setFont(font)
        self.edtNewCat.setObjectName("edtNewCat")
        self.verticalLayout_2.addWidget(self.edtNewCat)
        self.btnAddCat = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAddCat.setFont(font)
        self.btnAddCat.setObjectName("btnAddCat")
        self.verticalLayout_2.addWidget(self.btnAddCat)
        self.btnManageCats = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnManageCats.setFont(font)
        self.btnManageCats.setObjectName("btnManageCats")
        self.verticalLayout_2.addWidget(self.btnManageCats)
        self.btnCancel = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnCancel.setObjectName("btnCancel")
        self.verticalLayout_2.addWidget(self.btnCancel)
        self.actionDone = QtWidgets.QAction(ReadCheckFileDialog)
        self.actionDone.setObjectName("actionDone")

        self.retranslateUi(ReadCheckFileDialog)
        QtCore.QMetaObject.connectSlotsByName(ReadCheckFileDialog)

    def retranslateUi(self, ReadCheckFileDialog):
        _translate = QtCore.QCoreApplication.translate
        ReadCheckFileDialog.setWindowTitle(_translate("ReadCheckFileDialog", "Dialog"))
        self.label.setText(_translate("ReadCheckFileDialog", "<html><head/><body><p><span style=\" font-size:12pt; color:#55007f;\">Read New Checking File From:</span></p></body></html>"))
        self.filePathEdit.setToolTip(_translate("ReadCheckFileDialog", "Path to check file that was read."))
        self.listCategories.setToolTip(_translate("ReadCheckFileDialog", "<html><head/><body><p>List of currently defined categories. Select an entry from the Uncategorized list. Optionally select a unique string in the line edit above, then select a category from the list at the right and click Set Cat.</p></body></html>"))
        self.listCategories.setSortingEnabled(True)
        self.listCategorized.setToolTip(_translate("ReadCheckFileDialog", "List of check file entries that have already been categorized."))
        self.listCategorized.setSortingEnabled(True)
        self.edtSelectTrigger.setToolTip(_translate("ReadCheckFileDialog", "<html><head/><body><p>Entry selected from uncategorized list. Select a categorizing string, a category from the list at right and then click Set Cat.</p></body></html>"))
        self.listUnCategorized.setToolTip(_translate("ReadCheckFileDialog", "<html><head/><body><p>A list of check file entries, for which no category string was recognized. If there is a unique recognizable string in the entry, select that string, then select a category from list at the right and finally, click the Set Cat button.</p></body></html>"))
        self.listUnCategorized.setSortingEnabled(True)
        self.btnReadCheckFile.setToolTip(_translate("ReadCheckFileDialog", "<html><head/><body><p>Use file open dialog to select check file and read it.</p></body></html>"))
        self.btnReadCheckFile.setText(_translate("ReadCheckFileDialog", "Read File"))
        self.btnUnCat.setText(_translate("ReadCheckFileDialog", "UnCat Entry"))
        self.btnAccept.setText(_translate("ReadCheckFileDialog", "Accept"))
        self.btnSetTrigger.setToolTip(_translate("ReadCheckFileDialog", "<html><head/><body><p>This button creates a new trigger string. It also searchs the UnCategorized list and sets the Category of any entry that contains the new trigger string. The category must be selected from Category list above. If a unique string was first selected in the Line Edit, then that unique string is used to match any like entries in the Uncategorized list. They will all have their categories set automatically, same for all future entries.</p></body></html>"))
        self.btnSetTrigger.setText(_translate("ReadCheckFileDialog", "Set Trigger"))
        self.btnSetCat.setToolTip(_translate("ReadCheckFileDialog", "<html><head/><body><p>This button sets the category of the current selected ntry in the UnCategorized List. No trigger string is defined and only the selected entry is effected. This is inteneded for rare entries. Any future entries, that are similar, will require this same action because no trigger string was defined.</p><p><br/></p></body></html>"))
        self.btnSetCat.setText(_translate("ReadCheckFileDialog", "Set Cat"))
        self.edtNewCat.setToolTip(_translate("ReadCheckFileDialog", "<html><head/><body><p>If you need a new category, enter it in this field. Then click the Add Cat button. Then select the entry to which it applies, select a unique string in that entry, select your newly created entry from the category list and finally select Set Cat. All matching entries will be categorized.</p></body></html>"))
        self.btnAddCat.setToolTip(_translate("ReadCheckFileDialog", "<html><head/><body><p>Define a new category with the edit above, then use this button to add the new category to the list above.</p></body></html>"))
        self.btnAddCat.setText(_translate("ReadCheckFileDialog", "Add Cat"))
        self.btnManageCats.setToolTip(_translate("ReadCheckFileDialog", "<html><head/><body><p>Select an entry from the Category list, click this button and that category will be removed. All entries that were previously categorized with that category will become uncategorized and will be moved to the Uncategorized list. This includes all entries that have previously been categorized with that Category, so that they may be re-categorized. So be sure you want to delete a category. </p></body></html>"))
        self.btnManageCats.setText(_translate("ReadCheckFileDialog", "Manage Cats"))
        self.btnCancel.setText(_translate("ReadCheckFileDialog", "Cancel"))
        self.actionDone.setText(_translate("ReadCheckFileDialog", "Done"))
        self.actionDone.setShortcut(_translate("ReadCheckFileDialog", "Ctrl+D"))

