# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'what_if.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1351, 632)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(12, 12, 1321, 67))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(13)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboType = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboType.sizePolicy().hasHeightForWidth())
        self.comboType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboType.setFont(font)
        self.comboType.setObjectName("comboType")
        self.gridLayout_2.addWidget(self.comboType, 1, 5, 1, 1)
        self.comboCycle = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCycle.sizePolicy().hasHeightForWidth())
        self.comboCycle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboCycle.setFont(font)
        self.comboCycle.setObjectName("comboCycle")
        self.gridLayout_2.addWidget(self.comboCycle, 1, 6, 1, 1)
        self.labelCycle = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCycle.sizePolicy().hasHeightForWidth())
        self.labelCycle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelCycle.setFont(font)
        self.labelCycle.setObjectName("labelCycle")
        self.gridLayout_2.addWidget(self.labelCycle, 0, 6, 1, 1)
        self.editDate = QtWidgets.QDateEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editDate.sizePolicy().hasHeightForWidth())
        self.editDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editDate.setFont(font)
        self.editDate.setInputMethodHints(QtCore.Qt.ImhDate)
        self.editDate.setDate(QtCore.QDate(2017, 11, 21))
        self.editDate.setObjectName("editDate")
        self.gridLayout_2.addWidget(self.editDate, 1, 7, 1, 1)
        self.labelDate = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDate.sizePolicy().hasHeightForWidth())
        self.labelDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelDate.setFont(font)
        self.labelDate.setObjectName("labelDate")
        self.gridLayout_2.addWidget(self.labelDate, 0, 7, 1, 1)
        self.comboDate = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboDate.sizePolicy().hasHeightForWidth())
        self.comboDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboDate.setFont(font)
        self.comboDate.setObjectName("comboDate")
        self.gridLayout_2.addWidget(self.comboDate, 2, 7, 1, 1)
        self.buttonAdd = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAdd.sizePolicy().hasHeightForWidth())
        self.buttonAdd.setSizePolicy(sizePolicy)
        self.buttonAdd.setObjectName("buttonAdd")
        self.gridLayout_2.addWidget(self.buttonAdd, 2, 0, 1, 1)
        self.comboCat = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCat.sizePolicy().hasHeightForWidth())
        self.comboCat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboCat.setFont(font)
        self.comboCat.setObjectName("comboCat")
        self.gridLayout_2.addWidget(self.comboCat, 1, 2, 1, 1)
        self.chkboxIncome = QtWidgets.QCheckBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkboxIncome.sizePolicy().hasHeightForWidth())
        self.chkboxIncome.setSizePolicy(sizePolicy)
        self.chkboxIncome.setText("")
        self.chkboxIncome.setObjectName("chkboxIncome")
        self.gridLayout_2.addWidget(self.chkboxIncome, 1, 1, 1, 1)
        self.labelCat = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCat.sizePolicy().hasHeightForWidth())
        self.labelCat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelCat.setFont(font)
        self.labelCat.setObjectName("labelCat")
        self.gridLayout_2.addWidget(self.labelCat, 0, 2, 1, 1)
        self.labelAmount = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAmount.sizePolicy().hasHeightForWidth())
        self.labelAmount.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelAmount.setFont(font)
        self.labelAmount.setObjectName("labelAmount")
        self.gridLayout_2.addWidget(self.labelAmount, 0, 0, 1, 1)
        self.buttonDelete = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDelete.sizePolicy().hasHeightForWidth())
        self.buttonDelete.setSizePolicy(sizePolicy)
        self.buttonDelete.setObjectName("buttonDelete")
        self.gridLayout_2.addWidget(self.buttonDelete, 2, 2, 1, 1)
        self.buttonClear = QtWidgets.QPushButton(self.widget)
        self.buttonClear.setObjectName("buttonClear")
        self.gridLayout_2.addWidget(self.buttonClear, 2, 3, 1, 1)
        self.labelOver = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOver.sizePolicy().hasHeightForWidth())
        self.labelOver.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelOver.setFont(font)
        self.labelOver.setObjectName("labelOver")
        self.gridLayout_2.addWidget(self.labelOver, 0, 4, 1, 1)
        self.editAmount = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editAmount.sizePolicy().hasHeightForWidth())
        self.editAmount.setSizePolicy(sizePolicy)
        self.editAmount.setObjectName("editAmount")
        self.gridLayout_2.addWidget(self.editAmount, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.comboTrig = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboTrig.sizePolicy().hasHeightForWidth())
        self.comboTrig.setSizePolicy(sizePolicy)
        self.comboTrig.setObjectName("comboTrig")
        self.gridLayout_2.addWidget(self.comboTrig, 1, 3, 1, 1)
        self.label_Trig = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Trig.sizePolicy().hasHeightForWidth())
        self.label_Trig.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_Trig.setFont(font)
        self.label_Trig.setObjectName("label_Trig")
        self.gridLayout_2.addWidget(self.label_Trig, 0, 3, 1, 1)
        self.labelType = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelType.setFont(font)
        self.labelType.setObjectName("labelType")
        self.gridLayout_2.addWidget(self.labelType, 0, 5, 1, 1)
        self.buttonUpdate = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonUpdate.sizePolicy().hasHeightForWidth())
        self.buttonUpdate.setSizePolicy(sizePolicy)
        self.buttonUpdate.setObjectName("buttonUpdate")
        self.gridLayout_2.addWidget(self.buttonUpdate, 2, 1, 1, 1)
        self.comboOver = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboOver.sizePolicy().hasHeightForWidth())
        self.comboOver.setSizePolicy(sizePolicy)
        self.comboOver.setObjectName("comboOver")
        self.gridLayout_2.addWidget(self.comboOver, 1, 4, 1, 1)
        self.editComment = QtWidgets.QLineEdit(self.widget)
        self.editComment.setObjectName("editComment")
        self.gridLayout_2.addWidget(self.editComment, 1, 8, 1, 1)
        self.labelComment = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelComment.sizePolicy().hasHeightForWidth())
        self.labelComment.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelComment.setFont(font)
        self.labelComment.setObjectName("labelComment")
        self.gridLayout_2.addWidget(self.labelComment, 0, 8, 1, 1)
        self.gridLayout_2.setColumnStretch(8, 3)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(13, 86, 1321, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.graphicsView = QtWidgets.QGraphicsView(self.splitter)
        self.graphicsView.setObjectName("graphicsView")
        self.listWidget = QtWidgets.QListWidget(self.splitter)
        self.listWidget.setMinimumSize(QtCore.QSize(256, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(419, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1351, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelCycle.setText(_translate("MainWindow", "Cycle"))
        self.labelDate.setText(_translate("MainWindow", "Date Expr"))
        self.buttonAdd.setText(_translate("MainWindow", "Add"))
        self.labelCat.setText(_translate("MainWindow", "Cat"))
        self.labelAmount.setText(_translate("MainWindow", "Amount"))
        self.buttonDelete.setText(_translate("MainWindow", "Delete"))
        self.buttonClear.setText(_translate("MainWindow", "Clear"))
        self.labelOver.setText(_translate("MainWindow", "Over"))
        self.label.setText(_translate("MainWindow", "Income"))
        self.label_Trig.setText(_translate("MainWindow", "Trig"))
        self.labelType.setText(_translate("MainWindow", "Type"))
        self.buttonUpdate.setText(_translate("MainWindow", "Update"))
        self.labelComment.setText(_translate("MainWindow", "Comment"))

